# air.toml

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]
exclude_file = []
include_dir = ["."]
watch_log = true
delve = false

[log]
color = true
timestamp = true

[dev]
log_target = "console"
